export interface SettingsItem {
    id: number;
    active: boolean;
    code: string;
    name: string;
    description8?: string | null;
    hasSettings: boolean;
    procMaterialcId?: number | null;
    procMaterialcActive?: boolean | null;
    procMaterialcDescription1?: string | null;
    procMaterialcExpire1?: number | null;
    procMaterialcPacksizeum?: number | null;
    procMaterialcStacksizeum?: number | null;
    procMaterialcPalletpsizeum?: number | null;
    procMaterialcPalletssizeum?: number | null;
    packagingCode?: string | null;
    packagingName?: string | null;
    pkPackagingCode?: string | null;
    pkPackagingName?: string | null;
    itPackagingCode?: string | null;
    itPackagingName?: string | null;
    procLayoutITCode?: string | null;
    procLayoutITName?: string | null;
    procLayoutPKCode?: string | null;
    procLayoutPKName?: string | null;
    expire1methodCode?: string | null;
    expire1methodName?: string | null;
    unitsId?: number | null;
    unitsType?: string | null;
}
